apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-list-resources-role
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces"]
  verbs: ["list", "get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["list", "get"]
