apiVersion: v1
kind: Service
metadata:
  labels:
    app: final-exam
  name: final-exam
  namespace: dilmurod-final
spec:
  ports:
  - nodePort: 32001
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: final-exam
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
