apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-resources-binding
subjects:
- kind: User
  name: dilmurod
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: my-list-resources-role
  apiGroup: rbac.authorization.k8s.io
