apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-printer
  namespace: dilmurod-final
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      completions: 10
      parallelism: 5
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - sh
            - -c
            - echo $NODE_NAME
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            image: nginx
            imagePullPolicy: Always
            name: nginx
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          - command:
            - /bin/sh
            - -c
            - echo $(hostname)
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            name: node-printer
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/2 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
