apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: final-exam
  namespace: dilmurod-final
spec:
  ingressClassName: nginx
  rules:
  - host: dilmurod-final-exam.sts404.uz
    http:
      paths:
      - backend:
          service:
            name: final-exam
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
