apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"busybox-echo","namespace":"dilmurod-final"},"spec":{"containers":[{"command":["sh","-c","echo 'The BEST DevOps COURSE!!!'"],"image":"busybox","name":"echo"}],"restartPolicy":"Never"}}
  name: busybox-echo
  namespace: dilmurod-final
spec:
  containers:
  - command:
    - sh
    - -c
    - echo 'The BEST DevOps COURSE!!!'
    image: busybox
    imagePullPolicy: Always
    name: echo
    resources: {}
