apiVersion: v1
kind: Service
metadata:
  name: frontend-something
  namespace: dilmurod-final
spec:
  ports:
  - nodePort: 31301
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-something
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
