apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-exam
  namespace: dilmurod-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-exam
  template:
    metadata:
      labels:
        app: final-exam
    spec:
      containers:
      - name: flask-app
        image: nvrbckdown/flask-app:final-exam
        env:
        - name: author
          value: "dilmurod"
        - name: message
          value: "Well DONE!"
        - name: pod
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: node
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ["/bin/sh", "-c"]
        args:
          - echo "{\"author\":\"$author\",\"message\":\"$message\",\"node\":\"$node\",\"pod\":\"$pod\"}"; sleep 3600
